databases:
  - name: life-grind-be
    databaseName: lifegrinddb01
    user: lifegrinddb01_user

services:
  - type: web
    name: life-grind-be
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: life-grind-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false