# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

production:
  <<: *default
  database: life_grind_backend_production
  username: <%= ENV['LIFE_GRIND_BACKEND_DATABASE_USERNAME'] %>
  password: <%= ENV['LIFE_GRIND_BACKEND_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: life_grind_backend_development
  username: <%= ENV['LIFE_GRIND_BACKEND_DATABASE_USERNAME'] %>
  password: <%= ENV['LIFE_GRIND_BACKEND_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: life_grind_backend_test
  username: <%= ENV['LIFE_GRIND_BACKEND_DATABASE_USERNAME'] %>
  password: <%= ENV['LIFE_GRIND_BACKEND_DATABASE_PASSWORD'] %>
 
